### ISSUE TITLE
Don't let me commit to blog.servo.org

### ISSUE THREAD

**Issue by paulrouget** [servo/blog.servo.org#121]
I just commited a change to blog.servo.org by mistake: 3add526bb0e7cf04107a96b147400b51a5c8ba11

Github allows me to edit a markdown file, and create PR, but I clicked on "Commit" instead of "Create a PR".

Maybe we should add something to prevent accidental commits.

**Comment by ghost** [comment]
It doesn't have a `master` branch, since we're using `gh-pages`. @larsbergstrom Does Github allow us to lock that branch?

**Comment by jdm** [comment]
We actually encourage people to commit directly to the blog when making small changes.
