### ISSUE TITLE
Link servo-starters from TWIS

### ISSUE THREAD

**Issue by edunham** [servo/blog.servo.org#31]
http://www.ifdown.net/servo-starters/ is cool! Please put the link on the blog so I can find it more easily next time I forget where it lives :mag: 

(also https://github.com/servo/servo-starters)

**Comment by jdm** [comment]
I think the goal is to host it on servo.org before we start linking it widely.

**Comment by edunham** [comment]
servo-starters is now at http://servo.github.io/servo-starters/ . Do you think that's a sufficiently official URL for it?

**Comment by KiChjang** [comment]
I think we'd best link to http://servo.org/starters instead (currently it redirects to http://servo.github.io/servo-starters). This'll future-proof the eventual migration to be under servo.org.

**Comment by metajack** [comment]
@KiChjang +1
