### ISSUE TITLE
Interview contributors and post them on the blog

### ISSUE THREAD

**Issue by jdm** [servo/blog.servo.org#86]
Simple, short formula with freeform responses:
- tell us about yourself
- why did you start contributing to Servo?
- what was challenging about your first contribution?
- what do you like about contributing to the project? what do you get out of it?
- any final thoughts you'd like to share?

**Comment by metajack** [comment]
+1 on this idea. If initial questions are consistent this is really easy to do, even if you allow followup questions from those. I did a similar thing a long time ago with XMPP interviews (examples: 
[cabulous](https://metajack.im/2010/01/05/xmpp-case-study-interview-cabulous/) [drakontas](https://metajack.im/2011/03/29/xmpp-case-study-interview-drakontas/)). I had an outline for how I constructed these similar to yours above, but I can no longer find those notes.

**Comment by edunham** [comment]
@jdm Got any opinions on how we should choose who to feature/interview?

**Comment by jdm** [comment]
I would start with contributors who have made at least 5 contributions to Servo, where the most recent contribution occurred during the past 30 days.

**Comment by Manishearth** [comment]
We should also include some of our reviewer volunteers.

**Comment by mrego** [comment]
Moved to https://github.com/servo/servo.org/issues/68
